import { Ionicons } from "@expo/vector-icons";
import { useState } from "react";
import { Button, ScrollView, Text, View } from "react-native";
import ImageUpload from "../../components/ImageUpload";
import { useAuth } from "../../context/AuthContext";
import "../global.css";

export default function Index() {
  const { setIsSignedIn } = useAuth();
  const [caption, setCaption] = useState<string | null>(null);

  const handleUploadSuccess = (data: string) => {
    console.log("Image uploaded successfully:", data);
    setCaption(data);
  };

  const handleUploadError = (error: string) => {
    console.error("Upload error:", error);
  };

  const handleSignOut = () => {
    setIsSignedIn(false);
  };

  return (
    <ScrollView className="flex-1 bg-white">
      <View className="flex-1 p-6">
        {/* Header */}
        <View className="mb-8">
          <Text className="text-3xl font-black text-gray-800 mb-2">
            Upload Image
          </Text>
          <Text className="text-gray-500 text-base">
            Take a photo or choose from your gallery
          </Text>
        </View>

        {/* Image Upload Component */}
        <ImageUpload
          onUploadSuccess={handleUploadSuccess}
          onUploadError={handleUploadError}
        />

        {/* Uploaded Image URL Display */}
        {caption && (
          <View className="mt-8 bg-white rounded-3xl p-3 shadow-sm border border-indigo-50">
            <View className="flex-row items-center justify-between mb-4">
              <View className="flex-row items-center">
                <View className="w-10 h-10 bg-indigo-50 rounded-full items-center justify-center mr-3">
                  <Ionicons name="sparkles" size={20} color="#6366f1" />
                </View>
                <Text className="text-xl font-bold text-gray-800">
                  Magic Caption
                </Text>
              </View>
              <View className="bg-green-100 px-3 py-1 rounded-full">
                <Text className="text-green-700 text-xs font-bold uppercase">
                  Success
                </Text>
              </View>
            </View>

            <View className="bg-gray-50 rounded-2xl p-5 border border-gray-100">
              <Text className="text-gray-800 text-lg leading-7 font-medium italic">
                "{caption}"
              </Text>
            </View>

            <View className="mt-4 flex-row justify-end items-center">
              <Ionicons
                name="logo-snapchat"
                size={16}
                color="#818cf8"
                className="mr-1"
              />
              <Text className="text-indigo-400 text-xs font-bold tracking-wider">
                GENERATED BY SNAPSAYS
              </Text>
            </View>
          </View>
        )}

        {/* Sign Out Button */}
        <View className="mt-8">
          <Button title="Sign Out" onPress={handleSignOut} color="#ef4444" />
        </View>
      </View>
    </ScrollView>
  );
}
